export interface Surah {
  number: number;
  name: string;
  arabic: string;
  verses: number;
}

export const SURAHS: Surah[] = [
  { number: 1, name: "Al-Fātiḥa", arabic: "الفاتحة", verses: 7 },
  { number: 2, name: "Al-Baqara", arabic: "البقرة", verses: 286 },
  { number: 3, name: "Āl ʿImrān", arabic: "آل عمران", verses: 200 },
  { number: 4, name: "An-Nisāʾ", arabic: "النساء", verses: 176 },
  { number: 5, name: "Al-Māʾida", arabic: "المائدة", verses: 120 },
  { number: 6, name: "Al-Anʿām", arabic: "الأنعام", verses: 165 },
  { number: 7, name: "Al-Aʿrāf", arabic: "الأعراف", verses: 206 },
  { number: 8, name: "Al-Anfāl", arabic: "الأنفال", verses: 75 },
  { number: 9, name: "At-Tawba", arabic: "التوبة", verses: 129 },
  { number: 10, name: "Yūnus", arabic: "يونس", verses: 109 },
  { number: 11, name: "Hūd", arabic: "هود", verses: 123 },
  { number: 12, name: "Yūsuf", arabic: "يوسف", verses: 111 },
  { number: 13, name: "Ar-Raʿd", arabic: "الرعد", verses: 43 },
  { number: 14, name: "Ibrāhīm", arabic: "إبراهيم", verses: 52 },
  { number: 15, name: "Al-Ḥijr", arabic: "الحجر", verses: 99 },
  { number: 16, name: "An-Naḥl", arabic: "النحل", verses: 128 },
  { number: 17, name: "Al-Isrāʾ", arabic: "الإسراء", verses: 111 },
  { number: 18, name: "Al-Kahf", arabic: "الكهف", verses: 110 },
  { number: 19, name: "Maryam", arabic: "مريم", verses: 98 },
  { number: 20, name: "Ṭā Hā", arabic: "طه", verses: 135 },
  { number: 21, name: "Al-Anbiyāʾ", arabic: "الأنبياء", verses: 112 },
  { number: 22, name: "Al-Ḥajj", arabic: "الحج", verses: 78 },
  { number: 23, name: "Al-Muʾminūn", arabic: "المؤمنون", verses: 118 },
  { number: 24, name: "An-Nūr", arabic: "النور", verses: 64 },
  { number: 25, name: "Al-Furqān", arabic: "الفرقان", verses: 77 },
  { number: 26, name: "Ash-Shuʿarāʾ", arabic: "الشعراء", verses: 227 },
  { number: 27, name: "An-Naml", arabic: "النمل", verses: 93 },
  { number: 28, name: "Al-Qaṣaṣ", arabic: "القصص", verses: 88 },
  { number: 29, name: "Al-ʿAnkabūt", arabic: "العنكبوت", verses: 69 },
  { number: 30, name: "Ar-Rūm", arabic: "الروم", verses: 60 },
  { number: 31, name: "Luqmān", arabic: "لقمان", verses: 34 },
  { number: 32, name: "As-Sajda", arabic: "السجدة", verses: 30 },
  { number: 33, name: "Al-Aḥzāb", arabic: "الأحزاب", verses: 73 },
  { number: 34, name: "Sabaʾ", arabic: "سبأ", verses: 54 },
  { number: 35, name: "Fāṭir", arabic: "فاطر", verses: 45 },
  { number: 36, name: "Yā Sīn", arabic: "يس", verses: 83 },
  { number: 37, name: "Aṣ-Ṣāffāt", arabic: "الصافات", verses: 182 },
  { number: 38, name: "Ṣād", arabic: "ص", verses: 88 },
  { number: 39, name: "Az-Zumar", arabic: "الزمر", verses: 75 },
  { number: 40, name: "Ghāfir", arabic: "غافر", verses: 85 },
  { number: 41, name: "Fuṣṣilat", arabic: "فصلت", verses: 54 },
  { number: 42, name: "Ash-Shūrā", arabic: "الشورى", verses: 53 },
  { number: 43, name: "Az-Zukhruf", arabic: "الزخرف", verses: 89 },
  { number: 44, name: "Ad-Dukhān", arabic: "الدخان", verses: 59 },
  { number: 45, name: "Al-Jāthiya", arabic: "الجاثية", verses: 37 },
  { number: 46, name: "Al-Aḥqāf", arabic: "الأحقاف", verses: 35 },
  { number: 47, name: "Muḥammad", arabic: "محمد", verses: 38 },
  { number: 48, name: "Al-Fatḥ", arabic: "الفتح", verses: 29 },
  { number: 49, name: "Al-Ḥujurāt", arabic: "الحجرات", verses: 18 },
  { number: 50, name: "Qāf", arabic: "ق", verses: 45 },
  { number: 51, name: "Adh-Dhāriyāt", arabic: "الذاريات", verses: 60 },
  { number: 52, name: "Aṭ-Ṭūr", arabic: "الطور", verses: 49 },
  { number: 53, name: "An-Najm", arabic: "النجم", verses: 62 },
  { number: 54, name: "Al-Qamar", arabic: "القمر", verses: 55 },
  { number: 55, name: "Ar-Raḥmān", arabic: "الرحمن", verses: 78 },
  { number: 56, name: "Al-Wāqiʿa", arabic: "الواقعة", verses: 96 },
  { number: 57, name: "Al-Ḥadīd", arabic: "الحديد", verses: 29 },
  { number: 58, name: "Al-Mujādila", arabic: "المجادلة", verses: 22 },
  { number: 59, name: "Al-Ḥashr", arabic: "الحشر", verses: 24 },
  { number: 60, name: "Al-Mumtaḥana", arabic: "الممتحنة", verses: 13 },
  { number: 61, name: "Aṣ-Ṣaff", arabic: "الصف", verses: 14 },
  { number: 62, name: "Al-Jumuʿa", arabic: "الجمعة", verses: 11 },
  { number: 63, name: "Al-Munāfiqūn", arabic: "المنافقون", verses: 11 },
  { number: 64, name: "At-Taghābun", arabic: "التغابن", verses: 18 },
  { number: 65, name: "Aṭ-Ṭalāq", arabic: "الطلاق", verses: 12 },
  { number: 66, name: "At-Taḥrīm", arabic: "التحريم", verses: 12 },
  { number: 67, name: "Al-Mulk", arabic: "الملك", verses: 30 },
  { number: 68, name: "Al-Qalam", arabic: "القلم", verses: 52 },
  { number: 69, name: "Al-Ḥāqqa", arabic: "الحاقة", verses: 52 },
  { number: 70, name: "Al-Maʿārij", arabic: "المعارج", verses: 44 },
  { number: 71, name: "Nūḥ", arabic: "نوح", verses: 28 },
  { number: 72, name: "Al-Jinn", arabic: "الجن", verses: 28 },
  { number: 73, name: "Al-Muzzammil", arabic: "المزمل", verses: 20 },
  { number: 74, name: "Al-Muddaththir", arabic: "المدثر", verses: 56 },
  { number: 75, name: "Al-Qiyāma", arabic: "القيامة", verses: 40 },
  { number: 76, name: "Al-Insān", arabic: "الإنسان", verses: 31 },
  { number: 77, name: "Al-Mursalāt", arabic: "المرسلات", verses: 50 },
  { number: 78, name: "An-Nabaʾ", arabic: "النبأ", verses: 40 },
  { number: 79, name: "An-Nāziʿāt", arabic: "النازعات", verses: 46 },
  { number: 80, name: "ʿAbasa", arabic: "عبس", verses: 42 },
  { number: 81, name: "At-Takwīr", arabic: "التكوير", verses: 29 },
  { number: 82, name: "Al-Infiṭār", arabic: "الانفطار", verses: 19 },
  { number: 83, name: "Al-Muṭaffifīn", arabic: "المطففين", verses: 36 },
  { number: 84, name: "Al-Inshiqāq", arabic: "الانشقاق", verses: 25 },
  { number: 85, name: "Al-Burūj", arabic: "البروج", verses: 22 },
  { number: 86, name: "Aṭ-Ṭāriq", arabic: "الطارق", verses: 17 },
  { number: 87, name: "Al-Aʿlā", arabic: "الأعلى", verses: 19 },
  { number: 88, name: "Al-Ghāshiya", arabic: "الغاشية", verses: 26 },
  { number: 89, name: "Al-Fajr", arabic: "الفجر", verses: 30 },
  { number: 90, name: "Al-Balad", arabic: "البلد", verses: 20 },
  { number: 91, name: "Ash-Shams", arabic: "الشمس", verses: 15 },
  { number: 92, name: "Al-Layl", arabic: "الليل", verses: 21 },
  { number: 93, name: "Aḍ-Ḍuḥā", arabic: "الضحى", verses: 11 },
  { number: 94, name: "Ash-Sharḥ", arabic: "الشرح", verses: 8 },
  { number: 95, name: "At-Tīn", arabic: "التين", verses: 8 },
  { number: 96, name: "Al-ʿAlaq", arabic: "العلق", verses: 19 },
  { number: 97, name: "Al-Qadr", arabic: "القدر", verses: 5 },
  { number: 98, name: "Al-Bayyina", arabic: "البينة", verses: 8 },
  { number: 99, name: "Az-Zalzala", arabic: "الزلزلة", verses: 8 },
  { number: 100, name: "Al-ʿĀdiyāt", arabic: "العاديات", verses: 11 },
  { number: 101, name: "Al-Qāriʿa", arabic: "القارعة", verses: 11 },
  { number: 102, name: "At-Takāthur", arabic: "التكاثر", verses: 8 },
  { number: 103, name: "Al-ʿAṣr", arabic: "العصر", verses: 3 },
  { number: 104, name: "Al-Humaza", arabic: "الهمزة", verses: 9 },
  { number: 105, name: "Al-Fīl", arabic: "الفيل", verses: 5 },
  { number: 106, name: "Quraysh", arabic: "قريش", verses: 4 },
  { number: 107, name: "Al-Māʿūn", arabic: "الماعون", verses: 7 },
  { number: 108, name: "Al-Kawthar", arabic: "الكوثر", verses: 3 },
  { number: 109, name: "Al-Kāfirūn", arabic: "الكافرون", verses: 6 },
  { number: 110, name: "An-Naṣr", arabic: "النصر", verses: 3 },
  { number: 111, name: "Al-Masad", arabic: "المسد", verses: 5 },
  { number: 112, name: "Al-Ikhlāṣ", arabic: "الإخلاص", verses: 4 },
  { number: 113, name: "Al-Falaq", arabic: "الفلق", verses: 5 },
  { number: 114, name: "An-Nās", arabic: "الناس", verses: 6 },
];